name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: release  # Optional: Use dedicated environment for publishing
    permissions:
      contents: read
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: |
        python -m build

    - name: Check package
      run: |
        twine check dist/*

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        # Uses OpenID Connect (OIDC) trusted publishing
        # No API token needed - PyPI verifies the workflow via OIDC
        # Repository must be configured on PyPI with:
        # - Owner: AhEsmaeili79
        # - Repository: oasist
        # - Workflow: publish-to-pypi.yml
        # - Environment: release (optional but recommended)
